#!/bin/bash

# ChameleonLink v1.0

trap 'printf "\n";stop;exit 1' 2

dependencies() {
    command -v php > /dev/null 2>&1 || { echo >&2 "PHP is not installed! Install it."; exit 1; }
    command -v curl > /dev/null 2>&1 || { echo >&2 "Curl is not installed! Install it."; exit 1; }
    command -v ssh > /dev/null 2>&1 || { echo >&2 "Openssh is not installed! Install it."; exit 1; }
    command -v unzip > /dev/null 2>&1 || { echo >&2 "Unzip is not installed! Install it."; exit 1; }
}

loading() {
    clear
    printf "\e[1;92m\n"
    for i in {1..15}
    do
        printf "\n"
        for j in $(seq 1 $i)
        do
            printf "\u2593"
        done
        for k in $(seq $i 15)
        do
            printf "\u2592"
        done
        printf " Loading ...\n"
        sleep 0.1
        clear
    done
}

banner() {
    loading
    clear
    printf "\n"
    printf "\e[1;92m      ____ _                               _       _       _      \e[0m\n"
    printf "\e[1;92m     / ___| |__  _ __ ___  _ __   ___  ___| |_ ___| |__   (_)___  \e[0m\n"
    printf "\e[1;92m    | |   | '_ \| '__/ _ \| '_ \ / _ \/ __| __/ __| '_ \  | / __| \e[0m\n"
    printf "\e[1;92m    | |___| | | | | | (_) | | | |  __/ (__| || (__| | | |_| \__ \ \e[0m\n"
    printf "\e[1;92m     \____|_| |_|_|  \___/|_| |_|\___|\___|\__\___|_| |_(_)_|___/ \e[0m\n"
    printf "\n"
    printf "\e[1;93m       .:.:.\e[0m\e[1;94m Phishing Tool by Cat404x \e[0m\e[1;93m.:.:.\e[0m\n\n"
    printf "  \e[101m\e[1;77m:: Disclaimer: Developers assume no liability and are not    ::\e[0m\n"
    printf "  \e[101m\e[1;77m:: responsible for any misuse or damage caused by ChameleonLink ::\e[0m\n"
    printf " \n"
    printf " \e[36;1m.:. Choose any social site which you want to hack .:.\e[0m\n"
    printf " \n"
}

menu() {
    printf " \e[1;31m[\e[0m\e[1;77m01\e[0m\e[1;31m]\e[0m\e[1;93m Facebook     \e[0m\e[1;31m[\e[0m\e[1;77m11\e[0m\e[1;31m]\e[0m\e[1;93m Twitch       \e[0m\e[1;31m[\e[0m\e[1;77m21\e[0m\e[1;31m]\e[0m\e[1;93m DeviantArt\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m02\e[0m\e[1;31m]\e[0m\e[1;93m Instagram    \e[0m\e[1;31m[\e[0m\e[1;77m12\e[0m\e[1;31m]\e[0m\e[1;93m Pinterest    \e[0m\e[1;31m[\e[0m\e[1;77m22\e[0m\e[1;31m]\e[0m\e[1;93m Badoo\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m03\e[0m\e[1;31m]\e[0m\e[1;93m Google       \e[0m\e[1;31m[\e[0m\e[1;77m13\e[0m\e[1;31m]\e[0m\e[1;93m Snapchat     \e[0m\e[1;31m[\e[0m\e[1;77m23\e[0m\e[1;31m]\e[0m\e[1;93m Origin\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m04\e[0m\e[1;31m]\e[0m\e[1;93m Microsoft    \e[0m\e[1;31m[\e[0m\e[1;77m14\e[0m\e[1;31m]\e[0m\e[1;93m Linkedin     \e[0m\e[1;31m[\e[0m\e[1;77m24\e[0m\e[1;31m]\e[0m\e[1;93m CryptoCoin\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m05\e[0m\e[1;31m]\e[0m\e[1;93m Netflix      \e[0m\e[1;31m[\e[0m\e[1;77m15\e[0m\e[1;31m]\e[0m\e[1;93m Ebay         \e[0m\e[1;31m[\e[0m\e[1;77m25\e[0m\e[1;31m]\e[0m\e[1;93m Yahoo\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m06\e[0m\e[1;31m]\e[0m\e[1;93m PayPal       \e[0m\e[1;31m[\e[0m\e[1;77m16\e[0m\e[1;31m]\e[0m\e[1;93m Dropbox      \e[0m\e[1;31m[\e[0m\e[1;77m26\e[0m\e[1;31m]\e[0m\e[1;93m Wordpress\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m07\e[0m\e[1;31m]\e[0m\e[1;93m Steam        \e[0m\e[1;31m[\e[0m\e[1;77m17\e[0m\e[1;31m]\e[0m\e[1;93m Protonmail   \e[0m\e[1;31m[\e[0m\e[1;77m27\e[0m\e[1;31m]\e[0m\e[1;93m Yandex\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m08\e[0m\e[1;31m]\e[0m\e[1;93m Twitter      \e[0m\e[1;31m[\e[0m\e[1;77m18\e[0m\e[1;31m]\e[0m\e[1;93m Spotify      \e[0m\e[1;31m[\e[0m\e[1;77m28\e[0m\e[1;31m]\e[0m\e[1;93m StackoverFlow\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m09\e[0m\e[1;31m]\e[0m\e[1;93m PlayStation  \e[0m\e[1;31m[\e[0m\e[1;77m19\e[0m\e[1;31m]\e[0m\e[1;93m Reddit       \e[0m\e[1;31m[\e[0m\e[1;77m29\e[0m\e[1;31m]\e[0m\e[1;93m VK\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77m10\e[0m\e[1;31m]\e[0m\e[1;93m GitHub       \e[0m\e[1;31m[\e[0m\e[1;77m20\e[0m\e[1;31m]\e[0m\e[1;93m Adobe\e[0m\n"
    printf "\e[0m\n"
    printf " \e[1;31m[\e[0m\e[1;77mST\e[0m\e[1;31m]\e[0m\e[1;93m Termux Setup \e[1;31m[\e[0m\e[1;77mSL\e[0m\e[1;31m]\e[0m\e[1;93m Linux Setup  \e[0m\e[1;31m[\e[0m\e[1;77mEX\e[0m\e[1;31m]\e[0m\e[1;93m Exit\e[0m\n"
    printf "\e[0m\n"
    read -p $' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select an option: \e[0m\e[1;96m\en' option
    if [[ $option == 1 || $option == 01 ]]; then
        facebook
    elif [[ $option == 2 || $option == 02 ]]; then
        instagram
    elif [[ $option == 3 || $option == 03 ]]; then
        gmail
    elif [[ $option == 4 || $option == 04 ]]; then
        server="microsoft"
        start
    elif [[ $option == 5 || $option == 05 ]]; then
        server="netflix"
        start
    elif [[ $option == 6 || $option == 06 ]]; then
        server="paypal"
        start
    elif [[ $option == 7 || $option == 07 ]]; then
        server="steam"
        start
    elif [[ $option == 8 || $option == 08 ]]; then
        server="twitter"
        start
    elif [[ $option == 9 || $option == 09 ]]; then
        server="playstation"
        start
    elif [[ $option == 10 ]]; then
        server="github"
        start
    elif [[ $option == 11 ]]; then
        server="twitch"
        start
    elif [[ $option == 12 ]]; then
        server="pinterest"
        start
    elif [[ $option == 13 ]]; then
        server="snapchat"
        start
    elif [[ $option == 14 ]]; then
        server="linkedin"
        start
    elif [[ $option == 15 ]]; then
        server="ebay"
        start
    elif [[ $option == 16 ]]; then
        server="dropbox"
        start
    elif [[ $option == 17 ]]; then
        server="protonmail"
        start
    elif [[ $option == 18 ]]; then
        server="spotify"
        start
    elif [[ $option == 19 ]]; then
        server="reddit"
        start
    elif [[ $option == 20 ]]; then
        server="adobe"
        start
    elif [[ $option == 21 ]]; then
        server="deviantart"
        start
    elif [[ $option == 22 ]]; then
        server="badoo"
        start
    elif [[ $option == 23 ]]; then
        server="origin"
        start
    elif [[ $option == 24 ]]; then
        server="cryptocoinsniper"
        start
    elif [[ $option == 25 ]]; then
        server="yahoo"
        start
    elif [[ $option == 26 ]]; then
        server="wordpress"
        start
    elif [[ $option == 27 ]]; then
        server="yandex"
        start
    elif [[ $option == 28 ]]; then
        server="stackoverflow"
        start
    elif [[ $option == 29 ]]; then
        vk
    elif [[ $option == ST || $option == st ]]; then
        clear
        printf "\n\e[1;92mRunning Termux Setup "
        sleep 0.5
        printf "."
        sleep 0.5
        printf "."
        sleep 0.5
        printf ".\n\e[1;92m"
        apt update && apt upgrade -y
        pkg install wget curl php unzip openssh git -y
        printf "\n\e[1;92m Termux Setup Done ...\n\e[0m"
        sleep 1
        banner
        dependencies
        menu
    elif [[ $option == SL || $option == sl ]]; then
        clear
        printf "\n\e[1;92mRunning Linux Setup "
        sleep 0.5
        printf "."
        sleep 0.5
        printf "."
        sleep 0.5
        printf ".\n\e[1;92m"
        sudo apt install wget curl php unzip dos2unix ssh git -y
        printf "\n\e[1;92m Linux Setup Done ...\n\e[0m"
        sleep 1
        banner
        dependencies
        menu
    elif [[ $option == RE || $option == re ]]; then
        clear
        printf "\n\e[1;92mRestarting "
        sleep 0.5
        printf "."
        sleep 0.5
        printf "."
        sleep 0.5
        printf ".\n\e[1;92m"
        bash chameleonlink.sh
    elif [[ $option == EX || $option == ex ]]; then
        exit 1
    else
        printf " \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\e[1;93m Invalid option \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\n"
        sleep 1
        banner
        menu
    fi
}

start() {
    printf "Starting server for %s...\n" $server
    # Add server start logic here
}

facebook() {
    printf "Starting phishing for Facebook...\n"
    # Add Facebook phishing logic here
}

instagram() {
    printf "Starting phishing for Instagram...\n"
    # Add Instagram phishing logic here
}

gmail() {
    printf "Starting phishing for Gmail...\n"
    # Add Gmail phishing logic here
}

vk() {
    printf "Starting phishing for VK...\n"
    # Add VK phishing logic here
}

banner
dependencies
menu
